bugfix: when test a new app with ./manage.py test <newapp> it's fault with traceback shown below.
    django.db.utils.DatabaseError: relation "dynamic_field" does not exist
    LINE 1: ..."."choices", "dynamic_field"."default_value" FROM "dynamic_f...